[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[programs.localnet]
ido_pool = "4cNW81vB43u2GgqmK7zwsucCtQi1Yo6qYbiN7fpXroT6"

[programs.devnet]
ido_pool = "4cNW81vB43u2GgqmK7zwsucCtQi1Yo6qYbiN7fpXroT6"

[scripts]
init = "node ./scripts/init.js"
init-mock-spl = "node ./scripts/initMockSPLToken.js"
test = "yarn run mocha -t 1000000 tests/"
