[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[programs.localnet]
ido_pool = "HU2fHYFndVc8UX8fJmhK5ea3bC4UfUFLieNh18fEQ6ad"

[scripts]
init = "node ./scripts/init.js"
init-mock-spl = "node ./scripts/initMockSPLToken.js"
test = "yarn run mocha -t 1000000 tests/"
