[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
ido_pool = "2E3Zkp8bU3sHR3Y1YsnJFCVMKDUA3qDLUJ2jyZXNEYxz"

[scripts]
init = "node ./scripts/init.js"
test = "yarn run mocha -t 1000000 tests/"
